opBasic = function(a,b){
  print ("Suma")
  print (a+b)
  print ("Resta")
  print (a-b)
  print (b-a)
  print (paste(sprintf("%i - %i = ",a,b),a-b))
  print (paste(sprintf("%i - %i = ",b,a),b-a))
  print ("Producto")
  print (a*b)
  print ("Cociente de la division entera")
  print (a%/%b)
  print (b%/%a)
  print (paste(sprintf("%i : %i = ",a,b),a%/%b))
  print (paste("Con resto = ",a%%b))
  print (paste(sprintf("%i : %i = ",b,a),b%/%a))
  print (paste("Con resto = ",b%%a))
  print ("Resto de la division entera")
  print (a%%b)
  print (b%%a)
  print (paste(sprintf("Resto de %i : %i = ",a,b),a%%b))
  print (paste(sprintf("Resto de %i : %i = ",b,a),b%%a))
}
op